### ISSUE TITLE
Error loading shared library libgomp.so.1: No such file or directory

### ISSUE THREAD

**Issue by allways** [smizy/docker-scikit-learn#7]
I use "docker run -it --rm -p 8888:8888 -v $PWD:/code smizy/scikit-learn:0.22.2.post1-alpine" to run this image locally (windows10). But when I ran "from sklearn.linear_model import LinearRegression" in Notebook for the first time, this occurred:
> ImportError: Error loading shared library libgomp.so.1: No such file or directory (needed by /usr/lib/python3.8/site-packages/sklearn/utils/_openmp_helpers.cpython-38-x86_64-linux-gnu.so)

Is the libgomp not included in the alpine which here used?

**Comment by smizy** [comment]
@allways Thank you for reporting. I have pushed fixed image smizy/scikit-learn:0.22.2.post1-alpine-r1.
Please give it a try.

**Comment by allways** [comment]
> @allways Thank you for reporting. I have pushed fixed image smizy/scikit-learn:0.22.2.post1-alpine-r1.
> Please give it a try.

Strange, I download the image again but the error is still there. 
![image](https://user-images.githubusercontent.com/4850150/124664839-4c40fa00-deac-11eb-953e-866a59506aca.png)
![image](https://user-images.githubusercontent.com/4850150/124664737-2a477780-deac-11eb-87c3-ada8e92efe84.png)

**Comment by smizy** [comment]
@allways Use smizy/scikit-learn:0.22.2.post1-alpine-r1 instead of smizy/scikit-learn:0.22.2.post1-alpine.
Missing r1

**Comment by jussihuotari** [comment]
Ran into the same error, tried using the fixed image smizy/scikit-learn:0.22.2.post1-alpine-r1. It works. Thank you!
